name: app_fabinho_multimarcas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/carro1/carro1.jpg
    - lib/image/carro1/carro2.jpg
    - lib/image/carro1/carro3.jpg
    - lib/image/carro1/carro4.jpg
    - lib/image/carro1/carro5.jpg
    - lib/image/carro1/carro6.jpg
    - lib/image/logo/marca.png
